# This is the configuration file for a content generation tool. It contains settings that
# define how content is generated, as well as safety settings to ensure the content is
# appropriate. Additionally, it includes prompts for a model designed to analyze and
# provide structured outputs based on user-provided task descriptions.

# Configuration settings for the content generation process
GENERATION_CONFIG = {
    "temperature": 0.05,  # Controls the randomness of output generation
    "top_p": 0.1,  # Filters the cumulative probability for token selection
    "top_k": 1,  # Limits the number of highest probability tokens considered at each step
    "max_output_tokens": 1024,  # Maximum number of tokens in the output
}

# Safety settings for filtering out harmful content
SAFETY_SETTINGS = [
    {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE",
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE",
    },
]

# Predefined prompts for the model to structure its understanding and output
# of tasks based on user inputs. These prompts guide the model in identifying
# actionable items, timelines, and providing succinct advice, all while considering
# the language of input for appropriate response.
PROMPT_PARTS = [
    'Task: Design a to-do list app that interprets user-provided text inputs, determining whether action is required and, if so, identifying action/s, their respective timelines, and offering succinct advice. When analyzing the input, evaluate whether there is a verb in the sentence.  For example, "buy" is a verb, but "buying" is not. Automatically detect the language that used in input and give response with that language for just action, action_time and advice parameters. For example, if the input is English the response should be English, if the input is Turkish the response should be Turkish. Do not code! Do not create more than one actions. Do not create sub action. Do not fragmentate of the action. Do not give more than one advice. Input Format: Each input will contain a task or activity. Information will include whether the task requires actions (needs_actions: Yes), the specific actions needed (actions), the time frame or deadline for these actions (actions_time), and a concise advice (advice). Input/Output Format: Input: [Task description] need_action: [Yes/No] actions: [Action or actions] action_time: [Time frame or deadline] advice: [One or two pieces of advice related to the task]',
    "input: Send a birthday gift to my friend in Japan",
    "need_action Yes",
    "actions Purchase gift that you choose | Ship the gift",
    "action_time null",
    "advice Consider their interests and preferences when selecting a gift",
    "input: Tomorrow I'll do the weekly shop.",
    "need_action Yes",
    "actions Make shopping list | Purchase groceries",
    "action_time Tomorrow",
    "advice Plan your meals for the week and create a detailed shopping list to ensure you get everything you need",
    "input: Pizza night with friends this saturday",
    "need_action No",
    "actions null",
    "action_time Saturday",
    "advice null",
    "input: Send CV to companies",
    "need_action Yes",
    "actions Prepare the CV | Send the CV",
    "action_time null",
    "advice Tailor your CV to each specific job application, highlighting relevant skills and experience.",
    "input: Fix the broken light switch",
    "need_action Yes",
    "actions Fix the switch",
    "action_time null",
    "advice If attempting DIY repairs, ensure you turn off the power first",
    "input: Drinking water with friends",
    "need_action No",
    "actions Gather friends | Get water",
    "action_time null",
    "advice null",
    "input: Study exam this night",
    "need_action Yes",
    "actions Study exam",
    "action_time Tonight",
    "advice Break down the material into smaller chunks and study in intervals to improve retention",
    "input: Help to Karen",
    "need_action Yes",
    "actions Help Karen",
    "action_time null",
    "advice Be patient and understanding, and offer your support in any way you can",
    "input: Recharge Netflix subscription",
    "need_action Yes",
    "actions Renew Netflix subscription",
    "action_time null",
    "advice Recharge your subscription before it expires to avoid any interruption in service",
    "input: Upload the edited engagement photos",
    "need_action Yes",
    "actions Edit engagement photos | Upload enagagement photos",
    "action_time null",
    "advice When you upload your photos, give them descriptive filenames",
    "input: Mother's day gift pickup",
    "need_action Yes",
    "actions Pick up Mother's day gift",
    "action_time null",
    "advice Add a handwritten card or note to the gift for a personal touch",
    "input: Bu haftasonu sınavlarına çalışmayı unutma",
    "need_action Yes",
    "actions Sınavlara çalış",
    "action_time Bu haftasonu",
    "advice Sınavlara çalışırken düzenli aralıklarla mola verin ve çalıştığınız konuları tekrar gözden geçirin",
    "input: I have some money for Friday night",
    "need_action No",
    "actions null",
    "action_time Friday night",
    "advice null",
    "input: Buy flowers for Valentine's Day",
    "need_action Yes",
    "actions Buy flowers",
    "action_time Valentine's Day",
    "advice Choose flowers that are in season and that your loved one will appreciate",
    "input: Pay the payments",
    "need_action Yes",
    "actions Pay the payments",
    "action_time null",
    "advice Set up automatic payments to avoid late fees",
    "input: Walk with dog today at 18:00",
    "need_action Yes",
    "actions Walk with dog",
    "action_time Today at 18:00",
    "advice Choose a safe and enjoyable route for your walk",
    "input: Can you please assign dog walking at 18:00",
    "need_action Yes",
    "actions Walk with dog",
    "action_time Today at 18:00",
    "advice Make sure your dog has a collar and leash, and that you bring a bag to clean up after them",
    "input: Go to English class at 6 pm",
    "need_action Yes",
    "actions Attend English class",
    "action_time 6 pm",
    "advice Arrive early to get a good seat and participate actively in class discussions",
    "input: Paying the payments",
    "need_action Yes",
    "actions Pay the payments",
    "action_time null",
    "advice Set up automatic payments to avoid late fees",
    "input: Buying flowers for Valentine's Day",
    "need_action Yes",
    "actions Buy flowers",
    "action_time Valentine's Day",
    "advice Choose flowers that are in season and that your loved one will appreciate",
    "input: Pizza night with friends this Saturday at 20:00",
    "need_action Yes",
    "actions Make pizza | Invite friends",
    "action_time Saturday at 20:00",
    "advice Choose a variety of toppings and sides to make the pizza night more enjoyable",
    "input: There's a dog grooming appointment in two hours",
    "need_action Yes",
    "actions Take dog to grooming appointment | Pay for grooming services",
    "action_time In two hours",
    "advice Arrive a few minutes early for the appointment and provide the groomer with any special instructions you may have",
    "input: Yarın köpek için mama siparişi vermeyi unutma",
    "need_action Yes",
    "actions Sipariş ver",
    "action_time Yarın",
    "advice Mamayı seçerken köpeğinin diyetini gözden geçirmeyi unutma",
    "input: I like buying flowers",
    "need_action No",
    "actions null",
    "action_time null",
    "advice null",
    "input: There is a lesson after 2 noon on Friday",
    "need_action Yes",
    "actions Attend the lesson",
    "action_time Friday after 2 noon",
    "advice Arrive early to get a good seat and participate actively in class discussions",
    "input: Meeting with Kim",
    "need_action Yes",
    "actions Prepare for the meeting | Attend the meeting",
    "action_time null",
    "advice Do not be late",
    "input: Meet with Baran",
    "need_action Yes",
    "actions Meet with Baran",
    "action_time null",
    "advice Arrive early and come prepared with any relevant materials or information",
    "input: Buy foods for tomorrow's dinner and take kids from school at 4 pm",
    "need_action Yes",
    "actions Buy foods for tomorrow's dinner | Take kids from school at 4 pm",
    "action_time 4 pm",
    "advice Plan your meals ahead of time to ensure you have all the necessary ingredients and drive safe while with kids.",
    "input: Pay the bills and go to post office on Wednesday",
    "need_action Yes",
    "actions Pay the bills | Go to post office on Wednesday",
    "action_time Wednesday",
    "advice Set up automatic payments to avoid late fees and check the post office hours before you go",
]
